name: Update NovaProx Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update-configs:
    runs-on: self-hosted
    env:
      CARGO_INCREMENTAL: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Xray
        run: |
          # Download and install Xray
          wget -q -O Xray-linux-64.zip "$(wget -qO- https://api.github.com/repos/XTLS/Xray-core/releases/latest | grep -oP '"browser_download_url":\s*"\K[^"]*' | grep 'Xray-linux-64.zip' | head -n1)"
          unzip -o Xray-linux-64.zip
          sudo mv xray /usr/local/bin/
          sudo chmod +x /usr/local/bin/xray
          rm -f Xray-linux-64.zip LICENSE README.md
          
          # Verify installation
          xray -version

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Check for changes in source code
        id: check-changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            rust-src:
              - 'src/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'build.rs'

      - name: Build release binary (if needed)
        if: steps.check-changes.outputs.rust-src == 'true'
        run: cargo build --release
      
      - name: Use existing binary (if no changes)
        if: steps.check-changes.outputs.rust-src == 'false'
        run: |
          echo "Ð˜ÑÑ…Ð¾Ð´Ð½Ñ‹Ð¹ ÐºÐ¾Ð´ Ð½Ðµ Ð¸Ð·Ð¼ÐµÐ½Ð¸Ð»ÑÑ, Ð¿Ñ€Ð¾Ð²ÐµÑ€ÑÐµÐ¼ ÑÑƒÑ‰ÐµÑÑ‚Ð²ÑƒÑŽÑ‰Ð¸Ð¹ Ð±Ð¸Ð½Ð°Ñ€Ð½Ð¸Ðº..."
          
          if [ -f ./target/release/novaprox ]; then
            echo "âœ… Binary file found"
            ./target/release/novaprox --version || true
          else
            echo "âš ï¸ Binary file not found, building"
            cargo build --release
          fi

      - name: Update VLESS configs
        run: |
          ls
          sudo ./target/release/novaprox \
            --log-level debug \
            --chunk-size 100 \
            --max-concurrent-checks 25 \
            --out-file sub/vless.txt
        
      - name: Create primary config (first 10 VLESS)
        run: |
          head -n 10 sub/vless.txt > sub/primary.txt

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Generate random emoji
        id: emoji
        run: |
          EMOJIS=("âš¡" "ðŸ”¥" "âœ¨" "ðŸš€" "ðŸŒŸ" "ðŸ”§")
          SELECTED_EMOJI=${EMOJIS[$((RANDOM % ${#EMOJIS[@]}))]}
          echo "emoji=$SELECTED_EMOJI" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "${{ steps.emoji.outputs.emoji }} [${{ steps.date.outputs.date }}] Update subs"
          author_email: "actions@github.com"
          author_name: "GitHub Actions"
          add: "sub/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}